language: php
sudo: false

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update -q
  - composer install
  - composer update --prefer-lowest -n
  - composer update -n

cache:
  directories:
  - vendor

script:
  - composer test && composer ci
