language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
  - travis_retry composer install --no-interaction --prefer-source;
  - travis_retry composer update --prefer-source --no-interaction --prefer-stable;
script:
  - ./vendor/bin/phpcs --standard="./codesniffer.ruleset.xml" --colors src/Katana/*.php src/Katana/*/*.php && composer test
