language: php

sudo: false

php:
  - 5.5
  - 5.6

install:
  - travis_retry composer install --no-interaction --prefer-source;
  - travis_retry composer update --prefer-source --no-interaction --prefer-stable;
script:
  - composer test
